apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        image: jenkins-demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
spec:
  type: NodePort
  selector:
    app: jenkins-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
